cositas varias

diff --git a/.local/bin/dmenu/dm-pass b/.local/bin/dmenu/dm-pass
--- a/.local/bin/dmenu/dm-pass
+++ b/.local/bin/dmenu/dm-pass
@@ -2,29 +2,35 @@
 
 shopt -s nullglob globstar
 
+if [ -f $HOME/.dmenurc ]; then
+  . $HOME/.dmenurc
+else
+  DMENU='dmenu -h 18 -i'
+fi
+
 typeit=0
 if [[ $1 == "--type" ]]; then
 	typeit=1
 	shift
 fi
 
-if [[ -n $WAYLAND_DISPLAY ]]; then
-	dmenu=dmenu-wl
-	xdotool="ydotool type --file -"
-elif [[ -n $DISPLAY ]]; then
-	dmenu=dmenu
-	xdotool="xdotool type --clearmodifiers --file -"
-else
-	echo "Error: No Wayland or X11 display detected" >&2
-	exit 1
-fi
+# if [[ -n $WAYLAND_DISPLAY ]]; then
+# 	DMENU='dmenu-wl'
+# 	xdotool="ydotool type --file -"
+# elif [[ -n $DISPLAY ]]; then
+# 	DMENU='dmenu'
+# 	xdotool="xdotool type --clearmodifiers --file -"
+# else
+# 	echo "Error: No Wayland or X11 display detected" >&2
+# 	exit 1
+# fi
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
 password_files=( "$prefix"/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
-password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")
+password=$(printf '%s\n' "${password_files[@]}" | $DMENU "$@")
 
 [[ -n $password ]] || exit
 
